version: '3'
services:
   notebook-server:
      build: .
      ports:
         - "5000::5000"
      volumes:
         - ./:/mnt
      # entrypoint: bash -c "cd /mnt && jupyter notebook --NotebookApp.token='' --ip=0.0.0.0 --allow-root && /bin/bash" 
      stdin_open: true
      tty: true